### ISSUE TITLE
goog.object/set over aset

### ISSUE THREAD

**Issue by dotemacs** [eihli/cljs-react-native-starter#1]
https://github.com/eihli/cljs-react-native-starter/blob/8e9b6df66d93fe48295e497d931b3ab5223ca7c7/src/example/core.cljs#L184-L186

Good intuition, see the links below for confirmation, but `tl;dr`: `aset` & `aget` should only be used for arrays.

http://blog.fikesfarm.com/posts/2017-11-09-avoid-converting-javascript-objects.html

and a longer write up here:

https://clojurescript.org/news/2017-07-14-checked-array-access

In particular this:

> What should you use for object property access, if `aget` and `aset` are reserved for arrays? ClojureScript makes the Google Closure library readily accessible, and there are some nice facilities worth checking out in the goog.object namespace. In particular, `goog.object/get` and `goog.object/set` are appropriate APIs, suited for this purpose.

**Comment by eihli** [comment]
Updated comments with that info.
